name: Codespaces Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD }}
          POSTGRES_USER: ${{ secrets.PGUSER }}
          POSTGRES_DB: ${{ secrets.PGDATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Initialize Database
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        python -c "from utils.database import init_db; init_db()"
        
    - name: Run tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: ${{ secrets.PGDATABASE }}
      run: |
        pytest

    - name: Check formatting
      run: |
        black --check .
        flake8 .

    - name: Security check
      run: |
        pip install safety
        safety check
